### ISSUE TITLE
Training & testing on my own dataset 

### ISSUE THREAD

**Issue by abdur75648** [beratkurar/unsupervised_deep_learning_for_page_segmentation#2]
@beratkurar First of all thanks for your work.
I want to train this model on a dataset I've.
Please tell what should be the format & tree structure of the input images & ground truths (and also how they should be labeled).

Actually, I want to detect lines on my own dataset (It's line-wise annotated. The lines are rectangular & the annotation file contains 4 coordinate corners of each rectangle).
So, I would be thankful to you if you could please tell me how to train & test your model on my dataset?

**Comment by beratkurar** [comment]
This method does not input ground truths as it is an unsupervised learning method. Only your input images should be in binary form. This method can be used to segment pages into paragraphs and background, but not to segment into text lines.
You can find more details and visual explanations in this paper:

[Unsupervised Deep Learning for Handwritten Page
Segmentation](https://www.cs.bgu.ac.il/~berat/papers/icfhr2020_unsupervised_deep_learning_for_page_segmentation.pdf)

**Comment by abdur75648** [comment]
Thanks For Your Response
